/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layanan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class masyarakat extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    private final DateFormat dfl = new SimpleDateFormat("dd/MM/yyyy");
    Calendar hariIni;
    
    private DefaultTableModel model;
    public masyarakat() {
        initComponents();
        setLocationRelativeTo(this);
            conn = Koneksi.koneksi.KoneksiDB();
            
            model = new DefaultTableModel();
            jTable1.setModel(model);
            model.addColumn("NIK / ID Masyarakat");
            model.addColumn("Username");
            model.addColumn("Nama Lengkap");
            model.addColumn("Telpon");
            model.addColumn("Hak Akses"); 
            getData();
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
         @Override
         public void mouseClicked(java.awt.event.MouseEvent evt) {
        pilihData(); 
    }
});
    }
    
    void getData(){
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    
    try{
    String sql = "select * from masyarakat";
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
    
    while (rs.next()){
        Object[] obj = new Object[5];
        obj[0] = rs.getString("nik");
        obj[1] = rs.getString("username");
        obj[2] = rs.getString("nama");
        obj[3] = rs.getString("telp");
        obj[4] = rs.getString("level");
        model.addRow(obj);
    }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }
    
    void pilihData(){
        int i = jTable1.getSelectedRow();
        txt_nik.setText(model.getValueAt(i, 0).toString());
        txt_nama.setText(model.getValueAt(i, 1).toString());
        txt_username.setText(model.getValueAt(i, 2).toString());
        txt_telp.setText(model.getValueAt(i, 3).toString());
        cmb_level.setSelectedItem(model.getValueAt(i, 4).toString());
    }
    
    void bersih(){
        txt_nik.setText("");
        txt_nama.setText("");
        txt_pass.setText("");
        txt_username.setText("");
        txt_telp.setText("");
        cmb_level.setSelectedItem("");
        cmb_cari.setSelectedItem("");
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_telp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_level = new javax.swing.JComboBox<>();
        txt_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_cari = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        txt_ari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NIK / ID Masyarakat :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 29, -1, -1));

        jLabel2.setText("Nama :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 60, 104, -1));

        jLabel3.setText("Username :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 91, 71, -1));

        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 26, 196, -1));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 57, 196, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 88, 196, -1));

        jLabel5.setText("Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 122, 104, -1));

        jLabel6.setText("Telp :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 164, 104, -1));
        jPanel1.add(txt_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 161, 196, -1));

        jLabel7.setText("Hak Akses :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 197, 104, -1));

        cmb_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masyarakat", "Administrator", "Petugas" }));
        jPanel1.add(cmb_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 194, 196, -1));
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 119, 196, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 263, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 263, -1, -1));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 263, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 263, -1, -1));

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 263, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 485, 110));

        btn_cari.setText("CARI");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAMA" }));
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 150, -1));

        txt_ari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ariActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ari, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("FORM MASYARAKAT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 204, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/desainbaru.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sql = "insert into masyarakat (nik, nama, username, password, telp, level) values (?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_nik.getText());
            pst.setString(2, txt_nama.getText());
            pst.setString(3, txt_username.getText());
            pst.setString(4, txt_pass.getText());
            pst.setString(5, txt_telp.getText());
            pst.setString(6, cmb_level.getItemAt(cmb_level.getSelectedIndex()));
            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        getData();
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String nik = txt_nik.getText();
            String nama = txt_nama.getText();
            String username = txt_username.getText();
            String password = txt_pass.getText();
            String telp = txt_telp.getText();
            String level = cmb_level.getItemAt(cmb_level.getSelectedIndex());
            
            String sql = "UPDATE masyarakat set "
             + "nik = '" + nik + "', "
             + "nama = '" + nama + "', "
             + "username = '" + username + "', "
             + "password = '" + password + "', "
             + "telp = '" + telp + "', "
             + "level = '" + level + "' "
             + "WHERE nik = '" + nik + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATE SUKSES!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        getData(); 
        bersih();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bersih();
        getData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Apakah anda benar ingin menghaous data diatas?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from masyarakat where nik=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_nik.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "deleted");
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            getData();
            bersih();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nikActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String sql = "";
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            if (cmb_cari.getSelectedIndex() == 0){
                sql = "SELECT * FROM MASYARAKAT where nik like '%" + txt_ari.getText() + "%' ";
            }
            if (cmb_cari.getSelectedIndex() == 1) {
                sql = "SELECT * FROM MASYARAKAT where nama like '%" + txt_ari.getText() + "%' ";
            }
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()){
                Object[] obj = new Object[5];
                obj[0] = rs.getString("nik");
                obj[1] = rs.getString("username");
                obj[2] = rs.getString("nama");
                obj[3] = rs.getString("telp");
                obj[4] = rs.getString("level");
                
                model.addRow(obj);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_btn_cariActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_ariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masyarakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JComboBox<String> cmb_level;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_ari;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_telp;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
