/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layanan;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author IBNU
 */
public class pengaduan extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    private final DateFormat dfl = new SimpleDateFormat("dd/MM/yyyy");
    Calendar hariIni;
    
    private DefaultTableModel model;
    
   
    public pengaduan() {
        initComponents();
        setLocationRelativeTo(this);
        conn = Koneksi.koneksi.KoneksiDB(); //javaConnect = nama file c|| connectDB = nama method
        
        
        
       //memberi penamaan pada judul kolom ;
       model = new DefaultTableModel();
       jTable1.setModel(model);
       model.addColumn("id_pengaduan");
       model.addColumn("NIK");
       model.addColumn("Tanggal Pengaduan");
       model.addColumn("Isi Laporan");
       model.addColumn("Status");
       
       getData();//Memanggil getData
       jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
         @Override
         public void mouseClicked(java.awt.event.MouseEvent evt) {
             try { 
                 pilihData();
             } catch (ParseException ex) {
                 Logger.getLogger(pengaduan.class.getName()).log(Level.SEVERE, null, ex);
             }
    }
});
    }
    
    void getData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            //membuat statemen pemanggilan data pada table pada surat_masuk dari database
            String sql = "select * from pengaduan";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
        
            //penelusuran baris pada tabel surat_masuk dari database
            while (rs.next()) {
                Object[] obj = new Object[5];
                obj[0] = rs.getString("id_pengaduan");
                obj[1] = rs.getString("nik");
                obj[2] = rs.getString("tgl_pengaduan");
                obj[3] = rs.getString("isi_laporan");
                obj[4] = rs.getString("status");
                model.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void pilihData() throws ParseException {
        int i = jTable1.getSelectedRow();
        txt_pengaduan.setText(model.getValueAt(i, 0).toString());
        txt_nik.setText(model.getValueAt(i, 1).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse(model.getValueAt(i, 2).toString());
        jd_tglpengaduan.setDate(date);
        txt_isi.setText(model.getValueAt(i, 3).toString());
        txt_status.setText(model.getValueAt(i, 4).toString());
    }
    
    void bersih() {
        txt_pengaduan.setText("");
        txt_nama.setText("");
        txt_isi.setText("");
        txt_status.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pengaduan = new javax.swing.JTextField();
        txt_nik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jd_tglpengaduan = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_isi = new javax.swing.JTextArea();
        txt_status = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengaduan Fasilitas Sekolah");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID PENGADUAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 26, -1, -1));

        jLabel2.setText("NIK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 59, -1, -1));

        jLabel3.setText("NAMA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 91, -1, -1));
        jPanel1.add(txt_pengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 23, 220, -1));
        jPanel1.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 220, -1));

        jLabel4.setText("TANGGAL PENGADUAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 120, -1, -1));

        jLabel5.setText("ISI LAPORAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 145, -1, -1));

        jLabel7.setText("STATUS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 265, -1, -1));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 88, 220, -1));
        jPanel1.add(jd_tglpengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 114, 220, -1));

        txt_isi.setColumns(20);
        txt_isi.setRows(5);
        jScrollPane2.setViewportView(txt_isi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 145, 220, -1));
        jPanel1.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 220, -1));

        jButton7.setText("cek");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jButton8.setText("Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 346, -1, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 346, -1, -1));

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 346, -1, -1));

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 346, -1, -1));

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 346, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 346, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, 110));
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 301, -1));

        jButton6.setText("CARI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAMA" }));
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("FORM PENGADUAN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/desainbaru.jpeg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        String sql = "select * from masyarakat where nik='" + txt_nik.getText() + "'";
        try {
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("nama");
                txt_nama.setText(add1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
                
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(fm.format(jd_tglpengaduan.getDate()));
        try{
            String sql = "insert into pengaduan (id_pengaduan,nik,tgl_pengaduan,isi_laporan,status)values(?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_pengaduan.getText());
            pst.setString(2, (String) txt_nik.getText());
            pst.setString(3, tanggal);
            pst.setString(4, txt_isi.getText());
            pst.setString(5, txt_status.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        getData();
        bersih();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(fm.format(jd_tglpengaduan.getDate()));
        try {
            String id_pengaduan = txt_pengaduan.getText();
            String nik = txt_nik.getText();
            String tgl = tanggal;
            String isi = txt_isi.getText();
            String status = txt_status.getText();
            
            String sql = "UPDATE pengaduan set id_pengaduan='" + id_pengaduan + "', nik='" + nik + "', tgl_pengaduan='" + tgl + "', isi_laporan='" + isi + "', status='" + status + "' WHERE id_pengaduan='" + id_pengaduan + "'";
                    
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATE SUKSES");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        getData();
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bersih();
        getData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int p = JOptionPane.showConfirmDialog(null,
                "Apakah benar-benar akan dihapus permanen ? ",
                "Delete",
                JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from pengaduan where id_pengaduan=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_pengaduan.getText());
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "deleted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            getData();
            bersih();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String sql = "SELECT\n" +
"       pengaduan.id_pengaduan AS pengaduan_id_pengaduan, \n" +
"       pengaduan.nik AS pengaduan_nik, \n" +
"       pengaduan.tgl_pengaduan AS pengaduan_tgl_pengaduan, \n" +
"       pengaduan.isi_laporan AS pengaduan_isi_laporan, \n" +
"       pengaduan.status AS pengaduan_status, \n" +
"       masyarakat.nik AS masyarakat_nik, \n" +
"       masyarakat.nama AS masyarakat_nama, \n" +
"       masyarakat.username AS masyarakat_username, \n" +
"       masyarakat.password AS masyarakat_password, \n" +
"       masyarakat.telp AS masyarakat_telp, \n" +
"       masyarakat.level AS masyarakat_level \n" +
"       FROM masyarakat INNER JOIN pengaduan " +
"       ON masyarakat.nik = pengaduan.nik";

    try {
        String file = "F:\\NetBeansProjects\\layanan\\src\\report\\koneksi1.jasper";
        java.sql.Connection conn = Koneksi.koneksi.KoneksiDB();

        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Koneksi database null!");
            return;
        }

        java.io.File reportFile = new java.io.File(file);
        if (!reportFile.exists()) {
            JOptionPane.showMessageDialog(null, "File report tidak ditemukan di: " + reportFile.getAbsolutePath());
            return;
        }

        JasperPrint jp = JasperFillManager.fillReport(file, null, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Laporan: " + e.getMessage());
        e.printStackTrace();
    }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String sql = "";
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            if (cmb_cari.getSelectedIndex() == 0) {
                sql = "SELECT * FROM pengaduan where id_pengaduan like '%" + txt_cari.getText() + "%' ";
            }
            if (cmb_cari.getSelectedIndex() == 1) {
                sql = "SELECT * FROM pengaduan where nik like '%" + txt_cari.getText() + "%' ";
            }
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                Object[] obj = new Object[5];
                obj[0] = rs.getString("id_pengaduan");
                obj[1] = rs.getString("nik");
                obj[2] = rs.getString("tgl_pengaduan");
                obj[3] = rs.getString("isi_laporan");
                obj[4] = rs.getString("status");
                
                model.addRow(obj);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengaduan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengaduan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jd_tglpengaduan;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextArea txt_isi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_pengaduan;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
