/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layanan;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author IBNU
 */


public class tanggapan extends javax.swing.JFrame {

    /**
     * Creates new form tanggapan
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    private final DateFormat dfl = new SimpleDateFormat("dd/MM/yyyy");
    Calendar hariini;
    
    private DefaultTableModel model;
    public tanggapan() {
        initComponents();
        setLocationRelativeTo(this);
        conn = Koneksi.koneksi.KoneksiDB(); //javaConnect = nama file c|| connectDB = nama method

        
        
        //memberi penamaan pada judul kolom ;
       model = new DefaultTableModel();
       jTable1.setModel(model);
       model.addColumn("Id Tanggapan");
       model.addColumn("Id Pengaduan");
       model.addColumn("Tanggal Tanggapan");
       model.addColumn("Isi Laporan Tanggapan");
       model.addColumn("Id Petugas");
       
       getData();//Memanggil getData
       jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
         @Override
         public void mouseClicked(java.awt.event.MouseEvent evt) {
             try { 
                 pilihData();
             } catch (ParseException ex) {
                 Logger.getLogger(tanggapan.class.getName()).log(Level.SEVERE, null, ex);
             }
    }
});

    }
    
    //menampilkan data ke jTabel1
    void getData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            //membuat statemen pemanggilan data pada table pada surat_masuk dari database
            String sql = "select * from tanggapan";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
        
            //penelusuran baris pada tabel surat_masuk dari database
            while (rs.next()) {
                Object[] obj = new Object[5];
                obj[0] = rs.getString("id_tanggapan");
                obj[1] = rs.getString("id_pengaduan");
                obj[2] = rs.getString("tgl_tanggapan");
                obj[3] = rs.getString("tanggapan");
                obj[4] = rs.getString("id_petugas");
                
                model.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void pilihData() throws ParseException {
        int i = jTable1.getSelectedRow();
        txt_tanggapan.setText(model.getValueAt(i, 0).toString());
        txt_pengaduan.setText(model.getValueAt(i, 1).toString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse(model.getValueAt(i, 2).toString());
        txt_isi_tanggapan.setText(model.getValueAt(i, 3).toString());
        txt_idpetugas.setText(model.getValueAt(i, 4).toString());
        
    }
    void bersih() {
        txt_tanggapan.setText("");
        txt_pengaduan.setText("");
        txt_nama.setText("");
        txt_isi_tanggapan.setText("");
        txt_idpetugas.setText("");
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_tanggapan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_pengaduan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_isi_pengaduan = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jd_tgltanggapan = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_isi_tanggapan = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txt_idpetugas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        txt_cari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("From Tanggapan");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID TANGGAPAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 21, -1, -1));
        jPanel1.add(txt_tanggapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 18, 198, -1));

        jLabel2.setText("ID PENGADUAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 53, -1, -1));
        jPanel1.add(txt_pengaduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 50, 198, -1));

        jLabel3.setText("ISI LAPORAN PENGADUAN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 83, -1, -1));

        txt_isi_pengaduan.setColumns(20);
        txt_isi_pengaduan.setRows(5);
        jScrollPane1.setViewportView(txt_isi_pengaduan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 83, 198, -1));

        jLabel4.setText("TANGGAL TANGGAPAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 197, -1, -1));
        jPanel1.add(jd_tgltanggapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 190, 198, -1));

        jLabel5.setText("ISI LAPORAN TANGGAPAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 229, -1, -1));

        txt_isi_tanggapan.setColumns(20);
        txt_isi_tanggapan.setRows(5);
        jScrollPane2.setViewportView(txt_isi_tanggapan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 229, 198, -1));

        jLabel6.setText("ID PETUGAS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 340, -1, -1));
        jPanel1.add(txt_idpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 337, 198, -1));

        jLabel7.setText("NAMA PETUGAS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 377, -1, -1));

        jButton1.setText("Cek");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 49, -1, -1));

        jButton2.setText("Cek");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 336, -1, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 374, 198, -1));

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 476, -1, -1));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 476, -1, -1));

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 476, -1, -1));

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 476, -1, -1));

        jButton7.setText("Cetak");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 476, -1, -1));

        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 476, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 404, 130));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setText("FORM TANGGAPAN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jButton9.setText("CARI");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID PENGADUAN", "ID TANGGAPAN" }));
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 150, -1));
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 192, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/desainbaru.jpeg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String sql = "select * from pengaduan where id_pengaduan='" + txt_pengaduan.getText() + "'";
        try {
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("isi_laporan");
                txt_isi_pengaduan.setText(add1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String sql = "select * from petugas where id_petugas='" + txt_idpetugas.getText() + "'";
        try {
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("nama_petugas");
                txt_nama.setText(add1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(fm.format(jd_tgltanggapan.getDate()));
        try {
            String sql = "INSERT INTO tanggapan (id_tanggapan, id_pengaduan, tgl_tanggapan, tanggapan, id_petugas) values (?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql); // PASTIKAN INI ADA NILAINYA DAN ANGKA!
            pst.setString(1, txt_tanggapan.getText());
            pst.setString(2, txt_pengaduan.getText());
            pst.setString(3, tanggal);
            pst.setString(4, txt_isi_tanggapan.getText());
            pst.setString(5, txt_idpetugas.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        getData();
        bersih();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal=String.valueOf(fm.format(jd_tgltanggapan.getDate()));
        try {
            String id_tanggapan = txt_tanggapan.getText();
            String id_pengaduan = txt_pengaduan.getText();
            String tgl = tanggal;
            String isi = txt_isi_tanggapan.getText();
            String id_petugas = txt_idpetugas.getText();
            
            String sql = "UPDATE tanggapan set id_tanggapan='" + id_tanggapan + "', id_pengaduan='" + id_pengaduan + "', tgl_tanggapan='" + tgl + "', tanggapan='" + isi + "',id_petugas='" + id_petugas + "' where id_tanggapan='" + id_tanggapan + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "UPDATE SUKSES");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        getData();
        bersih();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        bersih();
        getData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int p = JOptionPane.showConfirmDialog(null,
                "Apakah benar-benar akan dihapus permanen ? ",
                "Delete",
                JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from tanggapan where id_tanggapan=?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_tanggapan.getText());
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "deleted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            getData();
            bersih();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String sql = "";
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            if (cmb_cari.getSelectedIndex() == 0) {
                sql = "SELECT * FROM tanggapan where id_pengaduan like '%" + txt_cari.getText() + "%' ";
            }
            if (cmb_cari.getSelectedIndex() == 1) {
                sql = "SELECT * FROM tanggapan where id_tanggapan like '%" + txt_cari.getText() + "%' ";
            }
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                Object[] obj = new Object[5];
                obj[0] = rs.getString("id_tanggapan");
                obj[1] = rs.getString("id_pengaduan");
                obj[2] = rs.getString("tgl_tanggapan");
                obj[3] = rs.getString("tanggapan");
                obj[4] = rs.getString("id_petugas");
                
                model.addRow(obj);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String sql = "SELECT\n" +
"       tanggapan.`id_tanggapan` AS tanggapan_id_tanggapan,\n" +
"       tanggapan.`id_pengaduan` AS tanggapan_id_pengaduan,\n" +
"       tanggapan.`tgl_tanggapan` AS tanggapan_tgl_tanggapan,\n" +
"       tanggapan.`tanggapan` AS tanggapan_tanggapan,\n" +
"       tanggapan.`id_petugas` AS tanggapan_id_petugas,\n" +
"       pengaduan.`id_pengaduan` AS pengaduan_id_pengaduan,\n" +
"       pengaduan.`nik` AS pengaduan_nik,\n" +
"       pengaduan.`tgl_pengaduan` AS pengaduan_tgl_pengaduan,\n" +
"       pengaduan.`isi_laporan` AS pengaduan_isi_laporan,\n" +
"       pengaduan.`status` AS pengaduan_status,\n" +
"       petugas.`id_petugas` AS petugas_id_petugas,\n" +
"       petugas.`nama_petugas` AS petugas_nama_petugas,\n" +
"       petugas.`username` AS petugas_username,\n" +
"       petugas.`password` AS petugas_password,\n" +
"       petugas.`telp` AS petugas_telp,\n" +
"       petugas.`level` AS petugas_level\n" +
"FROM\n" +
"       `pengaduan` pengaduan INNER JOIN `tanggapan` tanggapan ON pengaduan.`id_pengaduan` = tanggapan.`id_pengaduan`\n" +
"       INNER JOIN `petugas` petugas ON tanggapan.`id_petugas` = petugas.`id_petugas`";
        try {
        String file = "F:\\NetBeansProjects\\layanan\\src\\report\\tanggapan.jasper";
        java.sql.Connection conn = Koneksi.koneksi.KoneksiDB();

        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Koneksi database null!");
            return;
        }

        java.io.File reportFile = new java.io.File(file);
        if (!reportFile.exists()) {
            JOptionPane.showMessageDialog(null, "File report tidak ditemukan di: " + reportFile.getAbsolutePath());
            return;
        }

        JasperPrint jp = JasperFillManager.fillReport(file, null, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Laporan: " + e.getMessage());
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tanggapan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jd_tgltanggapan;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_idpetugas;
    private javax.swing.JTextArea txt_isi_pengaduan;
    private javax.swing.JTextArea txt_isi_tanggapan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pengaduan;
    private javax.swing.JTextField txt_tanggapan;
    // End of variables declaration//GEN-END:variables
}
